### ISSUE TITLE
CUDA error: no kernel image available

### ISSUE THREAD

**Issue by lkinman** [warpem/miss-alignment#107]
I'm trying to install and run miss-alignment on our system and am running into a CUDA error that's puzzling me a bit! 

Command and output are copied below. 

Command:

`OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 miss-alignment --config-file config.yaml --training-devices 0 --reconstruction-devices 1,1,1,1 --dataloaders-per-trainer 5 --start-at-iteration 0 --prepare-stacks 10.0
`

Output: 
```
Using devices [0] for training
Using devices [1, 1, 1, 1] for reconstruction
Using devices [0, 1] for alignment
[rank: 0] Seed set to 45132
Preparing stacks for 65 tilt series at 10.0 Å
Preparing stacks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [02:19<00:00,  2.15s/tilt series]
Successfully prepared stacks for 65 tilt series

============================================================
Iteration 1/8 - Alignment: anchoring
============================================================

/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/lightning/fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/lkinman/.conda/envs/missalignment/bin/miss-ali ...
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
Created pool directory: /tmp/recon_pool_fe4ffb73c881
Pool configuration: 4 workers -> 5 partitions (200 files each)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/lightning/pytorch/utilities/model_summary/model_summary.py:242: Precision 16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.
┏━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name      ┃ Type                     ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ criterion │ TripletMarginRankingLoss │      0 │ train │     0 │
│ 1 │ net       │ OptimizedModule          │  295 K │ train │     0 │
└───┴───────────┴──────────────────────────┴────────┴───────┴───────┘
Trainable params: 295 K                                                                                                                                                                                                                          
Non-trainable params: 0                                                                                                                                                                                                                          
Total params: 295 K                                                                                                                                                                                                                              
Total estimated model params size (MB): 1                                                                                                                                                                                                        
Modules in train mode: 29                                                                                                                                                                                                                        
Modules in eval mode: 0                                                                                                                                                                                                                          
Total FLOPs: 0                                                                                                                                                                                                                                   
Training:   0%|                                                                                                                                                                                                      | 0/30000 [00:00<?, ?step/s]Reconstruction worker 1 starting (cycling through 5 partitions, 200 files each)
Reconstruction worker 0 starting (cycling through 5 partitions, 200 files each)
Reconstruction worker 2 starting (cycling through 5 partitions, 200 files each)
Reconstruction worker 3 starting (cycling through 5 partitions, 200 files each)
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/miss_alignment/data/_reconstruction_worker.py", line 180, in reconstruction_worker
    triplets = _create_pool_reconstruction(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/miss_alignment/data/_reconstruction_worker.py", line 342, in _create_pool_reconstruction
    aligned = tilt_series.reconstruct_subvolumes_single(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/warpylib/tilt_series/reconstruct_subvolumes.py", line 298, in reconstruct_subvolumes_single
    return reconstruct_subvolumes(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/warpylib/tilt_series/reconstruct_subvolumes.py", line 178, in reconstruct_subvolumes
    data_rec, weight_rec = torch_projectors.backproject_2d_to_3d_forw(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch_projectors/ops.py", line 264, in backproject_2d_to_3d_forw
    return _Backproject2DTo3D.apply(projections, weights, rotations, shifts, interpolation, oversampling, fourier_radius_cutoff)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch/autograd/function.py", line 576, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch_projectors/ops.py", line 479, in forward
    data_reconstruction, weight_reconstruction = torch.ops.torch_projectors.backproject_2d_to_3d_forw(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch/_ops.py", line 1243, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch/_library/autograd.py", line 111, in autograd_impl
    result = forward_no_grad(*args, Metadata(keyset, keyword_only_args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch/_library/autograd.py", line 40, in forward_no_grad
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkinman/.conda/envs/missalignment/lib/python3.11/site-packages/torch/_ops.py", line 836, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Probably of note is the fact that our system is using the newer RTX PRO 5000 Blackwell cards, which I know often throw these kind of errors when the PyTorch and CUDA versions aren't configured correctly. 

But I can verify that we're using torch == 2.8.0 and CUDA == 12.9 (consistent with install instructions), and running `torch.cuda.get_arch_list()` in python suggests that our versions should be compatible with `sm_120` compute capability. 

Happy to provide any more info that might be helpful!

**Comment by dtegunov** [comment]
Hi Laurel! Sorry, my bad. v0.11 of https://github.com/warpem/torch-projectors comes with Blackwell support for cu128 and cu129 now.

**Comment by McHaillet** [comment]
Thanks for reporting @lkinman !

I added a note to the installation instruction for the Blackwell cards

**Comment by lkinman** [comment]
Perfect, can confirm that it's working now. Thanks both!
